CREATE TABLE IF NOT EXISTS remedios (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        TEXT        NOT NULL,
    horario     TEXT        NOT NULL,
    tomado      BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE INDEX IF NOT EXISTS idx_remedios_created_at ON remedios (created_at);


ALTER TABLE remedios ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Acesso total para usuários autenticados"
    ON remedios
    FOR ALL
    USING (true)
    WITH CHECK (true);

-- ── Dados iniciais de exemplo ─────────────────────────────────────

INSERT INTO remedios (nome, horario, tomado) VALUES
     ('Paracetamol', '08:00', false),
   ('Vitamina C',  '12:00', false),
  ('Ômega 3',     '20:00', false);
