-- ────────────────────────────────────────────────────────────────────────────
-- setup.sql — Execute este script no SQL Editor do seu projeto Supabase.
--
-- Como acessar o SQL Editor:
--   1. Acesse https://supabase.com e abra o seu projeto
--   2. No menu lateral, clique em "SQL Editor"
--   3. Cole este conteúdo e clique em "Run"
-- ────────────────────────────────────────────────────────────────────────────

-- Tabela principal de remédios
CREATE TABLE IF NOT EXISTS remedios (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        TEXT        NOT NULL,
    horario     TEXT        NOT NULL,
    tomado      BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Índice para acelerar ordenação por data de criação
CREATE INDEX IF NOT EXISTS idx_remedios_created_at ON remedios (created_at);

-- Habilita Row Level Security (boa prática no Supabase)
ALTER TABLE remedios ENABLE ROW LEVEL SECURITY;

-- Política: qualquer usuário autenticado pode ler e escrever
-- (ajuste conforme necessário para seu modelo de autenticação)
CREATE POLICY "Acesso total para usuários autenticados"
    ON remedios
    FOR ALL
    USING (true)
    WITH CHECK (true);

-- ── Dados iniciais de exemplo (opcional) ─────────────────────────────────────
-- Descomente as linhas abaixo se quiser popular a tabela para testar.

-- INSERT INTO remedios (nome, horario, tomado) VALUES
--     ('Paracetamol', '08:00', false),
--     ('Vitamina C',  '12:00', false),
--     ('Ômega 3',     '20:00', false);
