"""
db.py — Camada de persistência com Supabase (PostgreSQL em nuvem).

Substitui o antigo sistema de arquivos JSON por um banco de dados real.
Configure as variáveis de ambiente SUPABASE_URL e SUPABASE_KEY antes de usar.

Estrutura da tabela SQL (execute no Supabase SQL Editor):
──────────────────────────────────────────────────────────
CREATE TABLE remedios (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        TEXT    NOT NULL,
    horario     TEXT    NOT NULL,
    tomado      BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ DEFAULT NOW()
);
──────────────────────────────────────────────────────────
"""

import os
from typing import Optional

from supabase import Client, create_client

TABLE = "remedios"


def _get_client() -> Client:
    """Cria e retorna o cliente Supabase usando variáveis de ambiente."""
    url = os.environ.get("SUPABASE_URL", "")
    key = os.environ.get("SUPABASE_KEY", "")
    if not url or not key:
        raise EnvironmentError(
            "Variáveis de ambiente SUPABASE_URL e SUPABASE_KEY não estão configuradas.\n"
            "Crie um arquivo .env ou exporte-as no terminal antes de executar a aplicação."
        )
    return create_client(url, key)


# ── Operações CRUD ────────────────────────────────────────────────────────────


def carregar_dados(client: Optional[Client] = None) -> list[dict]:
    """Retorna todos os remédios cadastrados, ordenados por id."""
    c = client or _get_client()
    response = c.table(TABLE).select("*").order("id").execute()
    return response.data or []


def adicionar_remedio_db(nome: str, horario: str, client: Optional[Client] = None) -> dict:
    """Insere um novo remédio no banco e retorna o registro criado."""
    c = client or _get_client()
    response = (
        c.table(TABLE)
        .insert({"nome": nome.strip(), "horario": horario.strip(), "tomado": False})
        .execute()
    )
    return response.data[0]


def marcar_tomado_db(remedio_id: int, client: Optional[Client] = None) -> dict:
    """Atualiza o campo 'tomado' para True no registro com o id informado."""
    c = client or _get_client()
    response = (
        c.table(TABLE).update({"tomado": True}).eq("id", remedio_id).execute()
    )
    return response.data[0]


def remover_remedio_db(remedio_id: int, client: Optional[Client] = None) -> dict:
    """Remove o remédio com o id informado e retorna o registro deletado."""
    c = client or _get_client()
    response = c.table(TABLE).delete().eq("id", remedio_id).execute()
    return response.data[0]


def resetar_dia_db(client: Optional[Client] = None) -> None:
    """Marca todos os remédios como não tomados (início de novo dia)."""
    c = client or _get_client()
    # neq("id", 0) é um filtro "sempre verdadeiro" para atualizar todas as linhas
    c.table(TABLE).update({"tomado": False}).neq("id", 0).execute()
